version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    command: conda run --no-capture-output -n fink_tom_env fink_tom/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env_file/.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fink_tom_default
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fink_tom_dev

volumes:
  postgres_data:
