services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    command: conda run --no-capture-output -n fink_tom_env gunicorn -c config/gunicorn/dev.py
    volumes:
      - static_volume:/home/tom_dir/fink-tom/fink_tom/staticfiles
    expose:
      - 8000
    env_file:
      - ./env_file/.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file/.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/tom_dir/fink-tom/fink_tom/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
