services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    command: conda run --no-capture-output -n fink_tom_env gunicorn fink_tom.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env_file/.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file/.env.prod.db

volumes:
  postgres_data:
