name: fink_tom_env
dependencies:
- python==3.10.13
- gunicorn
- pip
- pip:
  - tomtoolkit
  - psycopg2-binary
  - tom-alertstreams
  - fink-client
  - tom_registration
  - git+https://github.com/FusRoman/tom_registration.git@tom_registration#egg=tom_registration # fork of the initial
  # tom_registration plugin,add the new users to the Public group when they are approved.
  - slackclient