FROM ubuntu:22.04

# SHELL [ "/bin/bash", "--login", "-c"]

ENV FINK_TOM_HOME /home/tom_dir

WORKDIR $FINK_TOM_HOME
COPY . fink-tom
WORKDIR fink-tom

ENV PATH=${USRLIBS}/miniconda/bin:/usr/local/bin:${PATH}

# Install system build dependencies
RUN apt-get update \
    && apt-get -y install git wget netcat \
    && apt-get -y install build-essential

# install python and the dependencies
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh \
    && bash ~/miniconda.sh -b -p ${USRLIBS}/miniconda

RUN conda env create -f environment.yml

ENTRYPOINT ["./docker/entrypoint_dev.sh"]
